flowchart LR
    A["Application level<br/>JVM, .NET CLR"] --> L["Library level<br/>WINE, WABI, vCUDA"] --> O["OS level<br/>Jail, containers, Ensim"] --> H["Hardware abstraction<br/>layer level<br/>VMware, Virtual PC, Xen"] --> I["Instruction set<br/>architecture level<br/>BIRD, Dynamo, QEMU"]
