flowchart LR
    A[End User] --> B[Firewall]
    B --> C[Load Balancer]
    C --> D[Compute Power]
    D --> E[Virtual Machine Automation]
    E --> F[(Storage)]
    G[Software Owner] --> H[Virtual Machine Image]
    H --> F
